### ISSUE TITLE
Terminologies

### ISSUE THREAD

**Issue by oyamad** [nswa17/ShingakuMatching#8]
"Faculty" というと教員の集合体を指すような気がします．
ぱっと調べた感じ，学科も "Department" と名乗っているケースが多いようです．

科類は，[ここ](http://www.c.u-tokyo.ac.jp/eng_site/info/academics/zenki/intro2/)では "Stream" となってます (初めて聞いた)．

コードの内容の話ではないですが．

**Comment by nswa17** [comment]
単語の指摘すごくありがたいです！直しておきました
